#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only)

echo "Running lint + typecheck..."
npm run check
if [ $? -ne 0 ]; then
  echo "❌ Checks failed."
  exit 1
fi

# Restage files modified by formatter
for file in $STAGED_FILES; do
  if [ -f "$file" ]; then
    git add "$file"
  fi
done

echo "✅ Passed"
